// Generated by CoffeeScript 1.7.1
(function() {
  var coffee, header, indent;

  indent = require('gulp-indent');

  header = require('gulp-header');

  coffee = require('gulp-coffee');

  module.exports = function(settings) {
    return [
      indent({
        tabs: false,
        amount: 2
      }), header('define (require, exports, module) ->\n'), coffee()
    ];
  };

}).call(this);
